# Generated by Django 5.1.6 on 2025-06-22 04:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('code', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EmployeeProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_no', models.CharField(blank=True, max_length=100)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('gender', models.IntegerField(blank=True, db_comment='性别 男1/女2', null=True)),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MyadminDepartment',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('code', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'db_table': 'myadmin_department',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MyadminEmployeeprofile',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('work_no', models.CharField(max_length=100, unique=True)),
                ('gender', models.IntegerField(blank=True, db_comment='性别 男1/女2', null=True)),
                ('phone', models.CharField(max_length=20)),
                ('user_id', models.BigIntegerField(unique=True)),
            ],
            options={
                'db_table': 'myadmin_employeeprofile',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WmsBinStorage',
            fields=[
                ('id', models.CharField(db_comment='库位id', max_length=50, primary_key=True, serialize=False)),
                ('loc_id', models.CharField(blank=True, db_comment='库位编码', max_length=50, null=True, unique=True)),
                ('bin_level', models.IntegerField(blank=True, db_comment='层', null=True)),
                ('bin_row', models.IntegerField(blank=True, db_comment='排', null=True)),
                ('bin_column', models.IntegerField(blank=True, db_comment='列', null=True)),
                ('quantity', models.IntegerField(blank=True, db_comment='存储数量', null=True)),
                ('min_threshold', models.IntegerField(blank=True, db_comment='最小库存预警阈值', null=True)),
            ],
            options={
                'db_table': 'wms_bin_storage',
                'db_table_comment': '库位物料',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='WmsCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customers_id', models.CharField(blank=True, db_comment='企业代号', max_length=10, null=True, unique=True)),
                ('company_name', models.CharField(blank=True, db_comment='企业名称', max_length=20, null=True)),
                ('area', models.IntegerField(blank=True, db_comment='企业类型1镇内2镇外', null=True)),
                ('level', models.IntegerField(blank=True, db_comment='企业评级', null=True)),
                ('principal', models.CharField(blank=True, db_comment='负责人', max_length=10, null=True)),
                ('phone', models.CharField(blank=True, db_comment='负责人电话', max_length=10, null=True)),
                ('email', models.CharField(blank=True, db_comment='负责人邮箱', max_length=50, null=True)),
                ('gender', models.IntegerField(blank=True, db_comment='联系人性别1男2女', null=True)),
                ('create_at', models.DateTimeField(blank=True, db_comment='加入时间', null=True)),
            ],
            options={
                'db_table': 'wms_customer',
                'db_table_comment': '客户',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='WmsOutbound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orders_id', models.IntegerField(blank=True, db_comment='采购订单id', null=True)),
                ('name', models.CharField(blank=True, db_comment='物料名称', max_length=50, null=True)),
                ('product_id', models.IntegerField(blank=True, db_comment='SKU编号', null=True)),
                ('quantity', models.IntegerField(blank=True, db_comment='数量', null=True)),
                ('bin_id', models.IntegerField(blank=True, db_comment='库位编号', null=True)),
                ('user_id', models.IntegerField(blank=True, db_comment='操作员id', null=True)),
                ('create_at', models.DateTimeField(blank=True, db_comment='出库时间', null=True)),
                ('update_at', models.DateTimeField(blank=True, db_comment='更新时间', null=True)),
            ],
            options={
                'db_table': 'wms_outbound',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='WmsProductColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_id', models.CharField(blank=True, db_comment='颜色编号', max_length=10, null=True, unique=True)),
                ('color_name', models.CharField(blank=True, db_comment='颜色名称', max_length=10, null=True)),
            ],
            options={
                'db_table': 'wms_product_color',
                'db_table_comment': '布料颜色表',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='WmsProductFabricType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fabric_type_id', models.CharField(blank=True, db_comment='布料品种id', max_length=10, null=True, unique=True)),
                ('fabric_type_name', models.CharField(blank=True, db_comment='布料品种名称', max_length=10, null=True)),
            ],
            options={
                'db_table': 'wms_product_fabric_type',
                'db_table_comment': '布料品种表',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='WmsOrders',
            fields=[
                ('orders_id', models.IntegerField(db_comment='订单编号', primary_key=True, serialize=False)),
                ('total_amount', models.IntegerField(blank=True, db_comment='面料出库总量', null=True)),
                ('category', models.IntegerField(blank=True, db_comment='1：镇内订单  2：镇外订单', null=True)),
                ('payment_status', models.IntegerField(blank=True, db_comment='财务状态:1未到账/2已到账', null=True)),
                ('status', models.IntegerField(blank=True, db_comment='1:已拣货  2:未拣货', null=True)),
                ('qrcode', models.CharField(blank=True, db_comment='拣货单二维码', max_length=100, null=True)),
                ('create_at', models.DateTimeField(blank=True, db_comment='下单时间', null=True)),
                ('update_at', models.DateTimeField(blank=True, db_comment='更新时间', null=True)),
                ('customer', models.ForeignKey(blank=True, db_comment='采购企业代号', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='myadmin.wmscustomer', to_field='customers_id')),
                ('work_no', models.ForeignKey(blank=True, db_column='work_no', db_comment='拣货员工号', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='myadmin.myadminemployeeprofile', to_field='work_no')),
            ],
            options={
                'db_table': 'wms_orders',
                'db_table_comment': '销售订单表',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='WmsProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(blank=True, db_comment='产品编号', max_length=10, null=True, unique=True)),
                ('price', models.IntegerField(blank=True, db_comment='单价', null=True)),
                ('loc', models.ForeignKey(blank=True, db_comment='库位编码', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='myadmin.wmsbinstorage', to_field='loc_id')),
                ('color', models.ForeignKey(blank=True, db_comment='布料颜色id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='myadmin.wmsproductcolor', to_field='color_id')),
                ('fabric_type', models.ForeignKey(blank=True, db_comment='布料品种id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='myadmin.wmsproductfabrictype', to_field='fabric_type_id')),
            ],
            options={
                'db_table': 'wms_product',
                'db_table_comment': '产品信息表',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='WmsOrdersDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('price', models.FloatField(blank=True, db_comment='单价', null=True)),
                ('total_price', models.FloatField(blank=True, null=True)),
                ('create_at', models.DateTimeField(blank=True, db_comment='下单日期', null=True)),
                ('orders', models.ForeignKey(db_comment='订单编号', on_delete=django.db.models.deletion.DO_NOTHING, to='myadmin.wmsorders')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='myadmin.wmsproduct', to_field='product_id')),
            ],
            options={
                'db_table': 'wms_orders_detail',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='wmsbinstorage',
            name='product',
            field=models.ForeignKey(blank=True, db_comment='物料id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='myadmin.wmsproduct', to_field='product_id'),
        ),
        migrations.CreateModel(
            name='WmsStockCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expected_qty', models.IntegerField()),
                ('actual_qty', models.IntegerField()),
                ('difference', models.IntegerField(blank=True, null=True)),
                ('checked_by', models.CharField(blank=True, max_length=50, null=True)),
                ('check_time', models.DateTimeField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='myadmin.wmsproduct', to_field='product_id')),
            ],
            options={
                'db_table': 'wms_stock_check',
                'db_table_comment': '库存盘点记录表',
                'managed': True,
            },
        ),
    ]
