# Generated by Django 5.1.6 on 2025-06-18 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdersDetailWithDates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orders_id', models.IntegerField(db_comment='订单编号')),
                ('product_id', models.CharField(db_collation='utf8mb4_0900_ai_ci', max_length=45)),
                ('quantity', models.IntegerField()),
                ('price', models.FloatField(db_comment='单价')),
                ('total_price', models.FloatField()),
                ('status', models.CharField(db_collation='utf8mb4_0900_ai_ci', max_length=45)),
                ('create_at', models.DateTimeField(blank=True, db_comment='下单时间', null=True)),
                ('update_at', models.DateTimeField(blank=True, db_comment='更新时间', null=True)),
            ],
            options={
                'db_table': 'orders_detail_with_dates',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WmsOrders',
            fields=[
                ('user_id', models.IntegerField(blank=True, db_comment='操作员id', null=True)),
                ('create_at', models.DateTimeField(blank=True, db_comment='下单时间', null=True)),
                ('orders_id', models.IntegerField(db_comment='订单编号', primary_key=True, serialize=False)),
                ('total_amount', models.IntegerField(blank=True, db_comment='面料出库总量', null=True)),
                ('category', models.IntegerField(blank=True, db_comment='1：镇内订单  2：镇外订单', null=True)),
                ('payment_status', models.IntegerField(blank=True, db_comment='支付状态:1未支付/2已支付/3已退款', null=True)),
                ('update_at', models.CharField(blank=True, db_comment='更新时间', max_length=30, null=True)),
            ],
            options={
                'db_table': 'wms_orders',
                'db_table_comment': '销售订单表',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OrdersDetailWithDates',
            fields=[
                ('price', models.FloatField(db_comment='单价')),
                ('total_price', models.FloatField()),
                ('orders_id', models.IntegerField(db_comment='订单编号', primary_key=True, serialize=False)),
                ('product_id', models.CharField(max_length=45)),
                ('quantity', models.IntegerField()),
                ('status', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'wms_orders_detail',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WmsOutbound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orders_id', models.IntegerField(blank=True, db_comment='采购订单id', null=True)),
                ('name', models.CharField(blank=True, db_comment='物料名称', max_length=50, null=True)),
                ('product_id', models.IntegerField(blank=True, db_comment='SKU编号', null=True)),
                ('quantity', models.IntegerField(blank=True, db_comment='数量', null=True)),
                ('bin_id', models.IntegerField(blank=True, db_comment='库位编号', null=True)),
                ('user_id', models.IntegerField(blank=True, db_comment='操作员id', null=True)),
                ('create_at', models.DateTimeField(blank=True, db_comment='出库时间', null=True)),
                ('update_at', models.DateTimeField(blank=True, db_comment='更新时间', null=True)),
            ],
            options={
                'db_table': 'wms_outbound',
                'managed': False,
            },
        ),
    ]
